on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ main ]

name: CI

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          components: rustfmt, clippy
          profile: minimal
          target: x86_64-apple-darwin
          toolchain: nightly

      - name: Run fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Run clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Build Release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all
